package com.android.cuifypmanagementsystem.utils

object Constants {

    // Intent Global Actions
    const val INTENT_ACTION_EDIT_TEACHER = "INTENT_ACTION_EDIT_TEACHER"
    const val ACTION_EDIT_TEACHER_OBJECT = "ACTION_EDIT_TEACHER_OBJECT"

    const val ACTION_EDIT_BATCH = "ACTION_EDIT_BATCH"
    const val ACTION_OPEN_DETAILS_FOR_CLOSED_ACTIVITY = "ACTION_OPEN_DETAILS_FOR_CLOSED_ACTIVITY"

    const val ACTION_SELECT_FYP_HEAD = "ACTION_SELECT_FYP_HEAD"
    const val ACTION_SELECT_FYP_SECRETORY = "ACTION_SELECT_FYP_SECRETORY"
    const val ACTION_CHANGE_FYP_HEAD = "ACTION_CHANGE_FYP_HEAD"
    const val ACTION_CHANGE_FYP_SECRETORY = "ACTION_CHANGE_FYP_SECRETORY"
    const val ACTION_SELECT_FYP_ACTIVITY_BATCH = "ACTION_SELECT_FYP_ACTIVITY_BATCH"
    const val ACTION_SELECT_TEACHER_FOR_FYP_ACTIVITY = "ACTION_SELECT_TEACHER_FOR_FYP_ACTIVITY"

    // Log Global Tag
    const val GLOBAL_TESTING_TAG = "GLOBAL_TESTING_LOGGING_TAG"

}